config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks do 
    member do
      patch :toggle_completion
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :category
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  enum status: {
    pending: 0,
    in_progress: 1,
    in_review: 2,
    completed: 3
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle_completion]

  #get method all the tasks with index.html.erb
  def index 
    if params[:sort] == 'desc'
      @tasks = Task.order(status: :desc)
    else
      @tasks = Task.order(:status)
    end
    # @tasks = Task.all
  end

  #get method this method get user to the create but does not save to database
  def new
    @task = Task.new
    @categories = Category.all
  end

  #get method will retrieve the list with the specified id but update method will render this to perform crud operation 
  def edit
    @task = Task.find(params[:id])
    @categories = Category.all
  end

  #post method this allow user to create new list with presentation view new.html.erb
  def create
    @task = Task.new(task_params)
    @categories = Category.all
    if @task.save
      redirect_to task_path(@task)
      # format.html { redirect_to @task, notice: "Task was successfully created." }
    else
      render :new
    end
  end

  #get method retrieve the list with specified id with presention show.html.erb
  def show
    @task = Task.find(params[:id])
  end

  #put or patch method allow u to update with method edit
  def update
    @task = Task.find(params[:id])
    @categories = Category.all
    if @task.update(task_params)
      redirect_to tasks_path, notice: "Task successfully updated."
    else
      render :edit
    end
  end

  #delete method allow u to delete method after getting the list from specified id fyi : from function show
  def destroy
    @task.destroy!
    redirect_to tasks_path, notice: "Task successfully deleted."
    # redirect_to tasks_path, notice: "Task successfully deleted."
    # format.html{redirect_to task_path, notice: "Task Successfully deleted"}
  end

  def toggle_completion
    @task.update(is_completed: !@task.is_completed?)
    redirect_to tasks_path
  end

  # def toogle_status
  #   @task = Task.find(params[:id])
  # end



  private
  def set_task
    @task = Task.find(params[:id])
  end

  #allow only which parameteres are accessible 
  def task_params
    params.require(:task).permit(:name, :category_id, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">

  <% @categories.each do |category| %>
  <div style="border:1px solid black; border-radius: 10px;padding: 20px;">
    <%= render category %>
    <p>
      <%= link_to "Show this category", category, style: "background-color: green; color: white; padding: 10px 20px; text-decoration: none; margin: 5px 0;border-radius: 5px;"%>
    </p>
    </div>
  <% end %>
</div>
<div style="display:flex; flex-direction: row; justify-content: space-between; margin-top: 10px; padding: 0 20px">
<%= link_to "New category", new_category_path, style: "background-color: #00995f; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
<%= link_to "Back to Task", tasks_path, style: "background-color: #00995f; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
</div>

app/views/categories/new.html.erb
<div style="max-width: 600px; margin: 10px auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; background-color: #f9f9f9;">
<% content_for :title, "New category" %>

<h1>New category</h1>
<div style="margin-top: 10px">
<%= render "form", category: @category, style:"padding: 20px" %>
</div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :is_completed, style: "display: block" %>
    <%= form.check_box :is_completed %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Is completed:</strong>
    <%= task.is_completed %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= task.category_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing Task" %>

<h1 style="font-family: 'Poppins', sans-serif; color: #333; text-align: center; margin-bottom: 30px;">Edit Task</h1>

<div class="form-container" style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; background-color: #f9f9f9;">
  <%= form_with(model: @task, local: true) do |f| %>

    <div class="form-group" style="margin-bottom: 20px;">
      <%= f.label :name, "Task Name", style: "font-family: 'Poppins', sans-serif;" %>
      <%= f.text_field :name, style: "width: 80%; padding: 10px; margin-top: 5px; border-radius: 5px; border: 1px solid #ccc;" %>
    </div>

    <div class="form-group" style="margin-bottom: 20px;">
      <%= f.label :category_id, "Category", style: "font-family: 'Poppins', sans-serif;" %>
      <%= f.collection_select :category_id, @categories, :id, :name, prompt: "Select a category", style: "width: 100%; padding: 10px; margin-top: 5px; border-radius: 5px; border: 1px solid #ccc;" %>
    </div>

     <div class="form-group" style="margin-bottom: 20px;">
    <%= f.label :status,  style: "font-family: 'Poppins', sans-serif;" %>
    <%= f.select :status, Task.statuses.keys.map { |w| [w.humanize, w] }, prompt: "Select Status", style: "width: 100%; padding: 10px; margin-top: 5px; border-radius: 5px; border: 1px solid #ccc;" %>
    </div>

    <div class="form-group" style="text-align: center;">
      <%= f.submit "Save Task", style: "background-color: #0080FF; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-family: 'Poppins', sans-serif;" %>
    </div>

  <% end %>
</div>

<div style="margin-top: 20px; display: flex; justify-content: center; gap: 15px; font-family: 'Poppins', sans-serif;">

  <%= link_to "Back to Tasks", tasks_path, 
      style: "background-color: #888888; color: white; padding: 10px 25px; text-decoration: none; border-radius: 5px;" %>
</div>

app/views/tasks/index.html.erb
<div style="margin-left: 150px; margin-bottom: 20px;">
  <h1>Task List</h1>
  <div>
  <p> sort by : <%= link_to 'status ascending', tasks_path(sort: 'asc'), style: "color: #40B5AD" %> | <%= link_to 'status descending', tasks_path(sort: 'desc'), style: "color: #40B5AD" %>  </p>

  </div>


</div>

<table style="margin: auto; width: 80% ">
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Category <%= link_to '+ add new ', new_category_path, method: :delete, style: "color:black; margin-left: 20px;" %></th>
      <th>Status</th>
      <th>Is_Done</th>
      <th>Customize</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.category.name %></td>
        <td><%= task.status.humanize %></td>
        <td>
  <%= button_to task.is_completed? ? 'Not Yet' : 'Done', 
              toggle_completion_task_path(task), 
              method: :patch, 
              style: "background-color: #6495ED; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; width=50%" %>
</td>
        <td>
          <%= link_to 'Edit', edit_task_path(task),  style: "background-color: #0080FF; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
          <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' },  style: "background-color: red; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style="margin-top: 20px; text-align: center;">
  <%= link_to 'new task', new_task_path, style: "background-color: #40B5AD; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New Task" %>

<h1 style="font-family: 'Poppins', sans-serif; color: #333; text-align: center; margin-bottom: 30px;">Create New Todo</h1>
<div class="form-container" style="max-width: 600px; margin: 10px auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; background-color: #f9f9f9;">

<%= form_with(model: @task, local: true) do |f| %>
  <div class="form-group">
    <div style = "padding-bottom: 10px; font-weight: bold">
    <%= f.label :name, "Task Name" %>
    </div>
    <div style= "width: 300px;" >
    <%= f.text_field :name, class: "form-control", placeholder: "Enter task name" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select :category_id, @categories, :id, :name, prompt: "Select Category", class: "form-control" %>
  </div>

    <div class="form-group" style="text-align: center;">
      <%= f.submit "Submit", style: "background-color: #0080FF; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-family: 'Poppins', sans-serif;" %>
    </div>
  </div>
  <div style="margin-top: 20px; display: flex; justify-content: center; gap: 15px; font-family: 'Poppins', sans-serif;">

  <%= link_to "Back to Tasks", tasks_path, 
      style: "background-color: #888888; color: white; padding: 10px 25px; text-decoration: none; border-radius: 5px;" %>
</div>
<% end %>

app/views/tasks/show.html.erb
<h1 style="font-family: 'Poppins', sans-serif; color: #333; text-align: center; margin-bottom: 30px;">Task Detail</h1>
<div class="form-container" style="max-width: fit-content; margin: 10px auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; background-color: #f9f9f9;">
<table>
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Category</th>
      <th>Is Done</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Customize</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.name %></td>
      <td><%= @task.category.name %></td>
      <td><%= @task.is_completed? ? 'Yes' : 'No' %></td>
      <td><%=  @task.created_at.strftime("%Y-%m-%d") %></td>
      <td><%=  @task.updated_at.strftime("%Y-%m-%d") %></td>
      <td style="display: flex; justify-content: space-between;">
        <%= link_to 'Edit', edit_task_path(@task),  style: "height: 100%; background-color: #0080FF; color: white; margin: 2px; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
        <%= link_to 'Back to Tasks', tasks_path, style: "height: 100%; background-color: #0080FF; color: white;margin: 2px; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
        <%= button_to 'Delete', @category, method: :delete,  style: "height: 100%; background-color: red; color: margin: 2px;white; padding: 10px 20px; text-decoration: none; border-radius: 5px;" %>
      </td>
    </tr>
  </tbody>
</table>
</div>